title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
color_scheme: null
search_enabled: true
search_tokenizer_separator: /[\s/]+/
logo: "/assets/images/openEHR_nl_logo.png"
collections:
  zib_templates:
    output: true
    permalink: /:collection/:name
collections_dir: ZIBs-on-openEHR/docs
data_dir: ZIBs-on-openEHR/docs/_data
aux_links:
  "een project van openEHR Nederland":
    - "//openehr.nl/"
heading_anchors: false
exclude: ["Gemfile", "Gemfile.lock","ZIBs-on-openEHR"]
verbose: false
