title: "Remote theme example"
# remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
color_scheme: null
search_enabled: false
search_tokenizer_separator: /[\s/]+/
logo: "/assets/images/openEHR_nl_logo.png"
collections:
  zib_templates:
    output: true
aux_links:
  "een project van openEHR Nederland":
    - "//openehr.nl/"
heading_anchors: true
